# Generated by Django 4.2.13 on 2024-06-18 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLibrary', '0004_book_publisher_alter_book_cover_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ForeignKey(default='cover_default.png', null=True, on_delete=django.db.models.deletion.CASCADE, to='OnlineLibrary.photo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ForeignKey(default='photo_default.png', max_length=255, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='OnlineLibrary.photo'),
        ),
    ]
